
[font]
# Setting monospace font family by itself isn't enough; see also
# `~/.config/fontconfig/fonts.conf`, which forces use of an emoji-capable font.
normal.family = "monospace"
size = 8

[general]
import = [
    # "~/.config/alacritty/themes/themes/{theme}.toml"
    # "~/.config/alacritty/themes/themes/blood_moon.toml",
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
    # "~/.config/alacritty/themes/themes/gnome_terminal.toml",
    # "~/.config/alacritty/themes/themes/papercolor_dark.toml",
]

[terminal.shell]
program = "/usr/bin/bash"   # Use the command `whereis bash` or `which bash` to verify the location of your bash executable
args = ["-l"]

# Support shift+enter for newline in Claude Code.
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
