add_newline = true

# Uncomment the format=$character line for a barebones prompt;
# suitable for screenshots/documentation.
# format = "$character"

# Replace the "â¯" symbol in the prompt with "âœ"
#[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "ğŸŒ± "

[python]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[directory]
disabled = false
truncation_length = 50
truncate_to_repo = false
truncation_symbol = ".../"

[hostname]
disabled = false
ssh_only = false
